#!/usr/bin/env python3
"""PreToolUse guard for KB-protected files — the enforcement tier of the
KB write protocol.

Denies Write/Edit tool calls that target, inside any detected KB:
  - INDEX.md               (script-generated, never hand-edited)
  - LOG.md                 (append-only via kb_log.py, canonical format)
  - SCHEMA.md              (owner-controlled; modifications only, creation allowed)
  - existing sources/*     (append-only evidence; new files allowed, edits not)

KB detection is marker-based, not path-based: a KB root is any directory
containing SCHEMA.md or LOG.md, or declared via a .kmd.json ({"root": "<dir>"})
at the workspace root — so the KB directory can be named anything. A literal
`kb/` path component is kept as a bootstrap fallback for KBs that have no
markers yet.

Everything else is left to the normal permission system (no output = no
opinion). Bash writes are NOT intercepted — lint remains the backstop, by
design.

Works with Claude Code hook input (tool_input.file_path) and, best-effort,
with Codex apply_patch payloads (parses "*** Update File:" / "*** Add File:"
markers from the patch envelope). The denial is emitted in the calling
harness's dialect: Cursor (`permission: deny`, detected via
$CURSOR_PROJECT_DIR), Hermes (`decision: block`, detected via the
`pre_tool_call` event name), and Claude Code / Codex
(`hookSpecificOutput.permissionDecision: deny`) otherwise.

Fails open: any unexpected error exits 0 silently — a hook bug must never
break a session.
"""

import json
import os
import re
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import cast

# The canonical KB resolution lives in the bundled kmd-ingest skill. If the
# skill directory is missing (broken symlink, partial install), the hook has
# no opinion and exits 0 — fail open, never break the session.
sys.path.insert(
    0,
    str(
        (
            Path(__file__).resolve().parent.parent.parent
            / "skills"
            / "kmd-ingest"
            / "scripts"
        ).resolve()
    ),
)

# isort: off
try:
    from kb_common import kb_for_file
except Exception:  # hook boundary: fail open on a broken install
    sys.exit(0)
# isort: on

CODEX_PATCH_RE = re.compile(r"^\*\*\*\s+(Update|Add|Delete)\s+File:\s+(.+)$", re.M)


def kb_relative(path_str: str) -> Path | None:
    """Resolve the KB-relative path of a file, or None if not in a KB.

    Prefers marker/config-based detection (kb_common); falls back to a
    literal `kb` path component for marker-less, freshly created KBs.
    """
    p = Path(path_str)

    try:
        kb = kb_for_file(p)
        if kb is not None:
            return p.resolve().relative_to(kb.root)
    except Exception:  # noqa: S110 — hook boundary, fall back to the heuristic
        pass

    parts = p.parts
    for i, part in enumerate(parts):
        if part == "kb":
            return Path(*parts[i + 1 :])

    return None


def check_path(path_str: str, is_update: bool | None = None) -> str | None:
    """Return a denial reason for a protected KB path, or None to allow.

    Args:
      path_str: Filesystem path the tool call targets.
      is_update: True if known to modify an existing file (Codex Update
        File), False if known to create (Add File), None to check the
        filesystem.
    """
    rel = kb_relative(path_str)
    if rel is None or not rel.parts:
        return None

    name = rel.parts[0]
    if len(rel.parts) == 1:
        if name == "INDEX.md":
            return (
                "INDEX.md is generated by script from page frontmatter — never "
                "hand-edited. Run the recompile-index script instead."
            )
        if name == "LOG.md":
            return (
                "LOG.md is append-only via kb_log.py (kmd-ingest/kmd-lint skill "
                "scripts) — the canonical entry format is what lint checks. "
                "Use: python3 <skill>/scripts/kb_log.py --action ... --title ... --agent ..."
            )
        if name == "SCHEMA.md":
            exists = is_update if is_update is not None else Path(path_str).exists()
            if exists:
                return (
                    "SCHEMA.md is the KB owner's convention doc — propose changes "
                    "to the owner rather than editing directly."
                )
            return None

    if rel.parts[0] == "sources":
        exists = is_update if is_update is not None else Path(path_str).exists()
        if exists:
            return (
                "sources/ is append-only evidence — existing source files are "
                "never edited. Filing NEW raw material is allowed; if this file is "
                "wrong, file a corrected copy alongside it and note the supersession."
            )

    return None


def candidate_paths(tool_input: dict[str, object]) -> Iterator[tuple[str, bool | None]]:
    """Yield (path, is_update) candidates from harness tool payloads.

    `tool_input` is the raw payload from the hook event — a genuinely dynamic
    map read once here at the trust boundary. Path keys come in two dialects:
    snake_case (Claude Code, Hermes) and camelCase (opencode's write/edit
    args pass `filePath`).
    """
    for key in ("file_path", "filePath", "path", "notebook_path", "notebookPath"):
        file_path = tool_input.get(key)
        if isinstance(file_path, str):
            yield file_path, None
            break

    for key in ("patch", "input", "changes"):  # Codex apply_patch variants
        patch = tool_input.get(key)
        if isinstance(patch, str) and "*** " in patch:
            for verb, path in CODEX_PATCH_RE.findall(patch):
                yield path.strip(), verb in ("Update", "Delete")


def emit_denial(reason: str, event_name: object) -> None:
    """Print the denial in the calling harness's output dialect.

    Cursor sets $CURSOR_PROJECT_DIR (and expects `permission: deny`); Hermes
    names the event `pre_tool_call` (and expects `decision: block`); Claude
    Code and Codex share the `hookSpecificOutput` shape and are the default.
    """
    if os.environ.get("CURSOR_PROJECT_DIR"):
        print(
            json.dumps(
                {"permission": "deny", "user_message": reason, "agent_message": reason}
            )
        )
        return

    if event_name == "pre_tool_call":
        print(json.dumps({"decision": "block", "reason": reason}))
        return

    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            }
        )
    )


def main() -> None:
    # Hook boundary: any unexpected failure exits 0 with no output so a
    # guard bug can never block unrelated tool calls.
    try:
        # Trust boundary: the hook payload is raw JSON, read exactly once here.
        payload: object = json.load(sys.stdin)
        if not isinstance(payload, dict):
            sys.exit(0)
        payload_map = cast(dict[str, object], payload)
        raw_tool_input = payload_map.get("tool_input")
        if not isinstance(raw_tool_input, dict):
            sys.exit(0)
        tool_input = cast(dict[str, object], raw_tool_input)

        for path, is_update in candidate_paths(tool_input):
            reason = check_path(path, is_update)
            if reason:
                emit_denial(reason, payload_map.get("hook_event_name"))
                return
    except Exception:  # noqa: S110 — fail open by contract (see module docstring)
        pass

    sys.exit(0)


if __name__ == "__main__":
    main()
